### ISSUE TITLE
[1.x] Google Application Credentials file not found at path

### ISSUE THREAD

**Issue by fellypsantos** [imdhemy/laravel-in-app-purchases#269] opened 2023-01-28 00:50 UTC
### Liap version(s) affected

1.6.2

### Description

I'm trying to implement app subscripton workflow, I have followed many times the step by step tutorial about how to setup, but no success.

Everytime my listener receives a new purchase with `Imdhemy\Purchases\Events\GooglePlay\SubscriptionPurchased`, and I use the `$subscription = $event->getServerNotification()->getSubscription();` , I got the `Google Application Credentials file not found at the_path_here` error

### My development enviroment
- using Laragon to handle my laravel API
- using ngrok (provided by Laragon) to put my local API online over HTTPS
- editing my subscription in Google Play Console Developer, putting the endpoint URL provided by ngrok
- the Developer Console setup is working, also the push is working.
- my laravel project name is ```meucns.server```
- project root path is ```C:\laragon\www\meucns.server\```
- my credential file is stored at ```C:\laragon\www\meucns.server\server-credentials.json```
- my ```.env``` file contains the setting
```
GOOGLE_APPLICATION_CREDENTIALS="server-credentials.json"
```

### More complete log down below:

```
[2023-01-27 21:04:24] local.ERROR: Google Application Credentials file not found at C:\laragon\www\meucns.server\C:\laragon\www\meucns.server\server-credentials.json {"exception":"[object] (RuntimeException(code: 0): Google Application Credentials file not found at C:\\laragon\\www\\meucns.server\\C:\\laragon\\www\\meucns.server\\server-credentials.json at C:\\laragon\\www\\meucns.server\\vendor\\imdhemy\\laravel-purchases\\src\\ServiceProviders\\LiapServiceProvider.php:128)
[stacktrace]
#0 C:\\laragon\\www\\meucns.server\\vendor\\imdhemy\\laravel-purchases\\src\\ServiceProviders\\LiapServiceProvider.php(104): Imdhemy\\Purchases\\ServiceProviders\\LiapServiceProvider->registerConfig()
#1 C:\\laragon\\www\\meucns.server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(682): Imdhemy\\Purchases\\ServiceProviders\\LiapServiceProvider->register()
#2 C:\\laragon\\www\\meucns.server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\ProviderRepository.php(75): Illuminate\\Foundation\\Application->register(Object(Imdhemy\\Purchases\\ServiceProviders\\LiapServiceProvider))
#3 C:\\laragon\\www\\meucns.server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(659): Illuminate\\Foundation\\ProviderRepository->load(Array)
#4 C:\\laragon\\www\\meucns.server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#5 C:\\laragon\\www\\meucns.server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(237): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#6 C:\\laragon\\www\\meucns.server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(153): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#7 C:\\laragon\\www\\meucns.server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(137): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#8 C:\\laragon\\www\\meucns.server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#9 C:\\laragon\\www\\meucns.server\\public\\index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#10 {main}"
```

I really hope that isn't a bug, just me doing something wrong.

### How to reproduce

- setup a normal laraval api
- setup all the things provided for Android at https://imdhemy.com/laravel-iap-docs/ 
- share the localhost api using ngrok
- copy the ngrok api endpoint and edit the subscription `Endpoint URL`  in Google Play Console Developer
- buy a demo subscription on Android app
- Google Play Console Developer will push the notification to the local api
- the error should be registered in laravel's log file

### Possible Solution

I've noticed that the path generated inside `vendor\imdhemy\laravel-purchases\src\ServiceProviders\LiapServiceProvider.php`  is wrong.

❌ `$googleCredentials` generated is always`C:\laragon\www\meucns.server\C:\laragon\www\meucns.server\server-credentials.json`

✅ `$googleCredentials` should be `C:\laragon\www\meucns.server\server-credentials.json`

When I put a Log after the line `$googleCredentials = config(self::CONFIG_KEY . '.google_application_credentials');`
I can see that the path is correct most of the time, but it gets wrong only when I receive a `SubscriptionPurchased` event.

### LiapServiceProvider.php
```php
/**
 * Merges published configurations with default config
 */
private function registerConfig(): void
{
    $this->mergeConfigFrom(self::CONFIG_PATH, self::CONFIG_KEY);

    $googleCredentials = config(self::CONFIG_KEY . '.google_application_credentials');

    if ($googleCredentials !== null && !is_dir($googleCredentials)) {
        if (!file_exists($googleCredentials)) {
            throw new RuntimeException("Google Application Credentials file not found at $googleCredentials");
        }
        putenv('GOOGLE_APPLICATION_CREDENTIALS=' . $googleCredentials);
    }
}
```

**Comment by imdhemy** [comment] 2023-01-28 09:16
Looks like that the method `registerConfig()` is hit twice. This is strange. I could not reproduce the issue on my
local machine.

In the first time it sets the env variable using the base path of the project. In the second time it does the same 
but this results in a replication of the base path.

I will publish a fix for this issue, but still I am not sure why this method is hit twice.

**Closed** 2023-01-28 10:00 UTC
Labels: Bug

**Comment by imdhemy** [comment] 2023-01-28 10:03
Could you please confirm if this issue is fixed in v 1.6.3?

**Comment by fellypsantos** [comment] 2023-01-28 12:54
Confirmed, problem was solved! Thank you so much for the help, keep up the amazing work with that lib.

**Comment by berkayakin** [comment] 2023-06-25 18:33
Hi. I can reproduce the same error with v1.8.1

`
[2023-06-25 18:20:01] production.ERROR: Google Application Credentials file not found at /var/www/html/vanilla-api//var/www/html/vanilla-api/pc-api-xxx.json {"exception":"[object] (RuntimeException(code: 0): Google Application Credentials file not found at /var/www/html/vanilla-api//var/www/html/vanilla-api/pc-api-xxx.json at /var/www/html/vanilla-api/vendor/imdhemy/laravel-purchases/src/ServiceProviders/LiapServiceProvider.php:126)
[stacktrace]
#0 /var/www/html/vanilla-api/vendor/imdhemy/laravel-purchases/src/ServiceProviders/LiapServiceProvider.php(101): Imdhemy\\Purchases\\ServiceProviders\\LiapServiceProvider->registerConfig()
#1 /var/www/html/vanilla-api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(687): Imdhemy\\Purchases\\ServiceProviders\\LiapServiceProvider->register()
#2 /var/www/html/vanilla-api/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register()
#3 /var/www/html/vanilla-api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(664): Illuminate\\Foundation\\ProviderRepository->load()
#4 /var/www/html/vanilla-api/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#5 /var/www/html/vanilla-api/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(242): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#6 /var/www/html/vanilla-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Foundation\\Application->bootstrapWith()
#7 /var/www/html/vanilla-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(160): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#8 /var/www/html/vanilla-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#9 /var/www/html/vanilla-api/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#10 {main}
"} 
`

**Comment by imdhemy** [comment] 2023-06-25 19:33
Hey @berkayakin 
Please, double check your settings. Did you have a look on this line in the exception message?

```
Google Application Credentials file not found at /var/www/html/vanilla-api//var/www/html/vanilla-api/pc-api-xxx.json
```

The root path `/var/www/html/vanilla-api/` appears twice.

**Comment by berkayakin** [comment] 2023-06-25 22:00
Hey @imdhemy,
this is exactly same as in the original report:

`Credentials file not found at C:\laragon\www\meucns.server\C:\laragon\www\meucns.server\server-credentials.json`

**Comment by imdhemy** [comment] 2023-06-26 06:57
What is the value you are using for the configuration `GOOGLE_APPLICATION_CREDENTIALS` ? @berkayakin

**Comment by berkayakin** [comment] 2023-06-26 07:38
@imdhemy 
Inside the `liap` config: `'google_application_credentials' => base_path(env('GOOGLE_APPLICATION_CREDENTIALS')),`
and inside the `.env` file: `GOOGLE_APPLICATION_CREDENTIALS=pc-api-xxx.json`

**Comment by imdhemy** [comment] 2023-06-26 08:11
What about updating `liap.php` to :
'google_application_credentials' => env('GOOGLE_APPLICATION_CREDENTIALS'),`

**Comment by berkayakin** [comment] 2023-06-26 08:16
@imdhemy I don't think it'll look for the project root, where the file is located at then. If you are confident that this will work, I can try it. Please let me know.

**Comment by imdhemy** [comment] 2023-06-26 08:17
You just to debug it and find the value that works.

**Comment by berkayakin** [comment] 2023-06-26 09:05
I get the following error without `base_path`

Google Application `Credentials file not found at pc-api-xxx.json`.

When I print `config('liap.google_application_credentials')` in a controller, I get the following output: `/var/www/html/vanilla-api/pc-api-7325803779606872704-784-854fa4bcd71c.json`.

So everything looks good with the config. It seems like there is an issue with the library.

**Comment by berkayakin** [comment] 2023-07-01 13:14
@imdhemy 

I changed the env variable with the following:

`GOOGLE_APPLICATION_CREDENTIALS=/var/www/html/vanilla-api/pc-api-xxx.json`

Now I don't get the same error but I get the following:

Client error: `POST https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response:
{"error":"invalid_grant","error_description":"Invalid JWT Signature."}

I checked the keys on Google Cloud for the service account and everything looks good. I'm curious if this error can be somehow related to `GOOGLE_APPLICATION_CREDENTIALS` variable.

**Comment by imdhemy** [comment] 2023-07-03 07:49
Under the hood, we are using the [Google Auth library](https://github.com/googleapis/google-auth-library-php). The  `GOOGLE_APPLICATION_CREDENTIALS` is only used by it, we don't depend on it on our code. 

I'd suggest to generate a new auth file, and make sure it's user is connected to the project with right role/permissions. As the error is related to the Signature which comes from the private key stored in the JSON file.
